id: PA948987D
initial_creation_type: input
source_metadata:
  title: Lama Zhang Tsöndrü Drakpa
  language: en
  description: 'Texts by and about Lama Zhang Tsöndrü Drakpa (bla ma zhang brtson
    ''grus grags pa, 1123–1193), founder of the Tsalpa Kagyü:'
  volume:
    7b444b4368e543218421d13cff3912c6:
      title: Twelve and a Half Crippled Verses
      parent: Songs and Poems
created_at: '2022-03-01T00:34:12.188920'
last_modified_at: '2022-03-01T00:34:12.188926'
